/**
 * generated by Xtext 2.39.0
 */
package d4m.acc.query.d4MQuery;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Axis Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see d4m.acc.query.d4MQuery.D4MQueryPackage#getAxisExpr()
 * @model
 * @generated
 */
public interface AxisExpr extends EObject
{
} // AxisExpr
