/**
 * generated by Xtext 2.39.0
 */
package d4m.acc.query.d4MQuery;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see d4m.acc.query.d4MQuery.D4MQueryFactory
 * @model kind="package"
 * @generated
 */
public interface D4MQueryPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "d4MQuery";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://fhir.genalytics.platform/d4m/D4MQuery";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "d4MQuery";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  D4MQueryPackage eINSTANCE = d4m.acc.query.d4MQuery.impl.D4MQueryPackageImpl.init();

  /**
   * The meta object id for the '{@link d4m.acc.query.d4MQuery.impl.D4MQueryImpl <em>D4M Query</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see d4m.acc.query.d4MQuery.impl.D4MQueryImpl
   * @see d4m.acc.query.d4MQuery.impl.D4MQueryPackageImpl#getD4MQuery()
   * @generated
   */
  int D4M_QUERY = 0;

  /**
   * The feature id for the '<em><b>Query</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int D4M_QUERY__QUERY = 0;

  /**
   * The number of structural features of the '<em>D4M Query</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int D4M_QUERY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link d4m.acc.query.d4MQuery.impl.QueryExprImpl <em>Query Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see d4m.acc.query.d4MQuery.impl.QueryExprImpl
   * @see d4m.acc.query.d4MQuery.impl.D4MQueryPackageImpl#getQueryExpr()
   * @generated
   */
  int QUERY_EXPR = 1;

  /**
   * The feature id for the '<em><b>Row</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY_EXPR__ROW = 0;

  /**
   * The feature id for the '<em><b>Col</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY_EXPR__COL = 1;

  /**
   * The number of structural features of the '<em>Query Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY_EXPR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link d4m.acc.query.d4MQuery.impl.AxisExprImpl <em>Axis Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see d4m.acc.query.d4MQuery.impl.AxisExprImpl
   * @see d4m.acc.query.d4MQuery.impl.D4MQueryPackageImpl#getAxisExpr()
   * @generated
   */
  int AXIS_EXPR = 2;

  /**
   * The number of structural features of the '<em>Axis Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AXIS_EXPR_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link d4m.acc.query.d4MQuery.impl.RowColWildcardImpl <em>Row Col Wildcard</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see d4m.acc.query.d4MQuery.impl.RowColWildcardImpl
   * @see d4m.acc.query.d4MQuery.impl.D4MQueryPackageImpl#getRowColWildcard()
   * @generated
   */
  int ROW_COL_WILDCARD = 3;

  /**
   * The number of structural features of the '<em>Row Col Wildcard</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_COL_WILDCARD_FEATURE_COUNT = AXIS_EXPR_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link d4m.acc.query.d4MQuery.impl.RangeExprImpl <em>Range Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see d4m.acc.query.d4MQuery.impl.RangeExprImpl
   * @see d4m.acc.query.d4MQuery.impl.D4MQueryPackageImpl#getRangeExpr()
   * @generated
   */
  int RANGE_EXPR = 4;

  /**
   * The feature id for the '<em><b>From</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE_EXPR__FROM = AXIS_EXPR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>To</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE_EXPR__TO = AXIS_EXPR_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Range Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE_EXPR_FEATURE_COUNT = AXIS_EXPR_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link d4m.acc.query.d4MQuery.impl.ListExprImpl <em>List Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see d4m.acc.query.d4MQuery.impl.ListExprImpl
   * @see d4m.acc.query.d4MQuery.impl.D4MQueryPackageImpl#getListExpr()
   * @generated
   */
  int LIST_EXPR = 5;

  /**
   * The feature id for the '<em><b>Values</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_EXPR__VALUES = AXIS_EXPR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>List Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_EXPR_FEATURE_COUNT = AXIS_EXPR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link d4m.acc.query.d4MQuery.impl.StartsWithExprImpl <em>Starts With Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see d4m.acc.query.d4MQuery.impl.StartsWithExprImpl
   * @see d4m.acc.query.d4MQuery.impl.D4MQueryPackageImpl#getStartsWithExpr()
   * @generated
   */
  int STARTS_WITH_EXPR = 6;

  /**
   * The feature id for the '<em><b>Prefix</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STARTS_WITH_EXPR__PREFIX = AXIS_EXPR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Starts With Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STARTS_WITH_EXPR_FEATURE_COUNT = AXIS_EXPR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link d4m.acc.query.d4MQuery.impl.RegexExprImpl <em>Regex Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see d4m.acc.query.d4MQuery.impl.RegexExprImpl
   * @see d4m.acc.query.d4MQuery.impl.D4MQueryPackageImpl#getRegexExpr()
   * @generated
   */
  int REGEX_EXPR = 7;

  /**
   * The feature id for the '<em><b>Pattern</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGEX_EXPR__PATTERN = AXIS_EXPR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Regex Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGEX_EXPR_FEATURE_COUNT = AXIS_EXPR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link d4m.acc.query.d4MQuery.impl.LiteralExprImpl <em>Literal Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see d4m.acc.query.d4MQuery.impl.LiteralExprImpl
   * @see d4m.acc.query.d4MQuery.impl.D4MQueryPackageImpl#getLiteralExpr()
   * @generated
   */
  int LITERAL_EXPR = 8;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAL_EXPR__VALUE = AXIS_EXPR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Literal Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAL_EXPR_FEATURE_COUNT = AXIS_EXPR_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link d4m.acc.query.d4MQuery.D4MQuery <em>D4M Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>D4M Query</em>'.
   * @see d4m.acc.query.d4MQuery.D4MQuery
   * @generated
   */
  EClass getD4MQuery();

  /**
   * Returns the meta object for the containment reference '{@link d4m.acc.query.d4MQuery.D4MQuery#getQuery <em>Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Query</em>'.
   * @see d4m.acc.query.d4MQuery.D4MQuery#getQuery()
   * @see #getD4MQuery()
   * @generated
   */
  EReference getD4MQuery_Query();

  /**
   * Returns the meta object for class '{@link d4m.acc.query.d4MQuery.QueryExpr <em>Query Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Query Expr</em>'.
   * @see d4m.acc.query.d4MQuery.QueryExpr
   * @generated
   */
  EClass getQueryExpr();

  /**
   * Returns the meta object for the containment reference '{@link d4m.acc.query.d4MQuery.QueryExpr#getRow <em>Row</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Row</em>'.
   * @see d4m.acc.query.d4MQuery.QueryExpr#getRow()
   * @see #getQueryExpr()
   * @generated
   */
  EReference getQueryExpr_Row();

  /**
   * Returns the meta object for the containment reference '{@link d4m.acc.query.d4MQuery.QueryExpr#getCol <em>Col</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Col</em>'.
   * @see d4m.acc.query.d4MQuery.QueryExpr#getCol()
   * @see #getQueryExpr()
   * @generated
   */
  EReference getQueryExpr_Col();

  /**
   * Returns the meta object for class '{@link d4m.acc.query.d4MQuery.AxisExpr <em>Axis Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Axis Expr</em>'.
   * @see d4m.acc.query.d4MQuery.AxisExpr
   * @generated
   */
  EClass getAxisExpr();

  /**
   * Returns the meta object for class '{@link d4m.acc.query.d4MQuery.RowColWildcard <em>Row Col Wildcard</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Row Col Wildcard</em>'.
   * @see d4m.acc.query.d4MQuery.RowColWildcard
   * @generated
   */
  EClass getRowColWildcard();

  /**
   * Returns the meta object for class '{@link d4m.acc.query.d4MQuery.RangeExpr <em>Range Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Range Expr</em>'.
   * @see d4m.acc.query.d4MQuery.RangeExpr
   * @generated
   */
  EClass getRangeExpr();

  /**
   * Returns the meta object for the attribute '{@link d4m.acc.query.d4MQuery.RangeExpr#getFrom <em>From</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>From</em>'.
   * @see d4m.acc.query.d4MQuery.RangeExpr#getFrom()
   * @see #getRangeExpr()
   * @generated
   */
  EAttribute getRangeExpr_From();

  /**
   * Returns the meta object for the attribute '{@link d4m.acc.query.d4MQuery.RangeExpr#getTo <em>To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>To</em>'.
   * @see d4m.acc.query.d4MQuery.RangeExpr#getTo()
   * @see #getRangeExpr()
   * @generated
   */
  EAttribute getRangeExpr_To();

  /**
   * Returns the meta object for class '{@link d4m.acc.query.d4MQuery.ListExpr <em>List Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List Expr</em>'.
   * @see d4m.acc.query.d4MQuery.ListExpr
   * @generated
   */
  EClass getListExpr();

  /**
   * Returns the meta object for the attribute list '{@link d4m.acc.query.d4MQuery.ListExpr#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Values</em>'.
   * @see d4m.acc.query.d4MQuery.ListExpr#getValues()
   * @see #getListExpr()
   * @generated
   */
  EAttribute getListExpr_Values();

  /**
   * Returns the meta object for class '{@link d4m.acc.query.d4MQuery.StartsWithExpr <em>Starts With Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Starts With Expr</em>'.
   * @see d4m.acc.query.d4MQuery.StartsWithExpr
   * @generated
   */
  EClass getStartsWithExpr();

  /**
   * Returns the meta object for the attribute '{@link d4m.acc.query.d4MQuery.StartsWithExpr#getPrefix <em>Prefix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Prefix</em>'.
   * @see d4m.acc.query.d4MQuery.StartsWithExpr#getPrefix()
   * @see #getStartsWithExpr()
   * @generated
   */
  EAttribute getStartsWithExpr_Prefix();

  /**
   * Returns the meta object for class '{@link d4m.acc.query.d4MQuery.RegexExpr <em>Regex Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Regex Expr</em>'.
   * @see d4m.acc.query.d4MQuery.RegexExpr
   * @generated
   */
  EClass getRegexExpr();

  /**
   * Returns the meta object for the attribute '{@link d4m.acc.query.d4MQuery.RegexExpr#getPattern <em>Pattern</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pattern</em>'.
   * @see d4m.acc.query.d4MQuery.RegexExpr#getPattern()
   * @see #getRegexExpr()
   * @generated
   */
  EAttribute getRegexExpr_Pattern();

  /**
   * Returns the meta object for class '{@link d4m.acc.query.d4MQuery.LiteralExpr <em>Literal Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Literal Expr</em>'.
   * @see d4m.acc.query.d4MQuery.LiteralExpr
   * @generated
   */
  EClass getLiteralExpr();

  /**
   * Returns the meta object for the attribute '{@link d4m.acc.query.d4MQuery.LiteralExpr#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see d4m.acc.query.d4MQuery.LiteralExpr#getValue()
   * @see #getLiteralExpr()
   * @generated
   */
  EAttribute getLiteralExpr_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  D4MQueryFactory getD4MQueryFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link d4m.acc.query.d4MQuery.impl.D4MQueryImpl <em>D4M Query</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see d4m.acc.query.d4MQuery.impl.D4MQueryImpl
     * @see d4m.acc.query.d4MQuery.impl.D4MQueryPackageImpl#getD4MQuery()
     * @generated
     */
    EClass D4M_QUERY = eINSTANCE.getD4MQuery();

    /**
     * The meta object literal for the '<em><b>Query</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference D4M_QUERY__QUERY = eINSTANCE.getD4MQuery_Query();

    /**
     * The meta object literal for the '{@link d4m.acc.query.d4MQuery.impl.QueryExprImpl <em>Query Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see d4m.acc.query.d4MQuery.impl.QueryExprImpl
     * @see d4m.acc.query.d4MQuery.impl.D4MQueryPackageImpl#getQueryExpr()
     * @generated
     */
    EClass QUERY_EXPR = eINSTANCE.getQueryExpr();

    /**
     * The meta object literal for the '<em><b>Row</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUERY_EXPR__ROW = eINSTANCE.getQueryExpr_Row();

    /**
     * The meta object literal for the '<em><b>Col</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUERY_EXPR__COL = eINSTANCE.getQueryExpr_Col();

    /**
     * The meta object literal for the '{@link d4m.acc.query.d4MQuery.impl.AxisExprImpl <em>Axis Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see d4m.acc.query.d4MQuery.impl.AxisExprImpl
     * @see d4m.acc.query.d4MQuery.impl.D4MQueryPackageImpl#getAxisExpr()
     * @generated
     */
    EClass AXIS_EXPR = eINSTANCE.getAxisExpr();

    /**
     * The meta object literal for the '{@link d4m.acc.query.d4MQuery.impl.RowColWildcardImpl <em>Row Col Wildcard</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see d4m.acc.query.d4MQuery.impl.RowColWildcardImpl
     * @see d4m.acc.query.d4MQuery.impl.D4MQueryPackageImpl#getRowColWildcard()
     * @generated
     */
    EClass ROW_COL_WILDCARD = eINSTANCE.getRowColWildcard();

    /**
     * The meta object literal for the '{@link d4m.acc.query.d4MQuery.impl.RangeExprImpl <em>Range Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see d4m.acc.query.d4MQuery.impl.RangeExprImpl
     * @see d4m.acc.query.d4MQuery.impl.D4MQueryPackageImpl#getRangeExpr()
     * @generated
     */
    EClass RANGE_EXPR = eINSTANCE.getRangeExpr();

    /**
     * The meta object literal for the '<em><b>From</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RANGE_EXPR__FROM = eINSTANCE.getRangeExpr_From();

    /**
     * The meta object literal for the '<em><b>To</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RANGE_EXPR__TO = eINSTANCE.getRangeExpr_To();

    /**
     * The meta object literal for the '{@link d4m.acc.query.d4MQuery.impl.ListExprImpl <em>List Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see d4m.acc.query.d4MQuery.impl.ListExprImpl
     * @see d4m.acc.query.d4MQuery.impl.D4MQueryPackageImpl#getListExpr()
     * @generated
     */
    EClass LIST_EXPR = eINSTANCE.getListExpr();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIST_EXPR__VALUES = eINSTANCE.getListExpr_Values();

    /**
     * The meta object literal for the '{@link d4m.acc.query.d4MQuery.impl.StartsWithExprImpl <em>Starts With Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see d4m.acc.query.d4MQuery.impl.StartsWithExprImpl
     * @see d4m.acc.query.d4MQuery.impl.D4MQueryPackageImpl#getStartsWithExpr()
     * @generated
     */
    EClass STARTS_WITH_EXPR = eINSTANCE.getStartsWithExpr();

    /**
     * The meta object literal for the '<em><b>Prefix</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STARTS_WITH_EXPR__PREFIX = eINSTANCE.getStartsWithExpr_Prefix();

    /**
     * The meta object literal for the '{@link d4m.acc.query.d4MQuery.impl.RegexExprImpl <em>Regex Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see d4m.acc.query.d4MQuery.impl.RegexExprImpl
     * @see d4m.acc.query.d4MQuery.impl.D4MQueryPackageImpl#getRegexExpr()
     * @generated
     */
    EClass REGEX_EXPR = eINSTANCE.getRegexExpr();

    /**
     * The meta object literal for the '<em><b>Pattern</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REGEX_EXPR__PATTERN = eINSTANCE.getRegexExpr_Pattern();

    /**
     * The meta object literal for the '{@link d4m.acc.query.d4MQuery.impl.LiteralExprImpl <em>Literal Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see d4m.acc.query.d4MQuery.impl.LiteralExprImpl
     * @see d4m.acc.query.d4MQuery.impl.D4MQueryPackageImpl#getLiteralExpr()
     * @generated
     */
    EClass LITERAL_EXPR = eINSTANCE.getLiteralExpr();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LITERAL_EXPR__VALUE = eINSTANCE.getLiteralExpr_Value();

  }

} //D4MQueryPackage
