/**
 * generated by Xtext 2.39.0
 */
package d4m.acc.query.d4MQuery;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>D4M Query</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link d4m.acc.query.d4MQuery.D4MQuery#getQuery <em>Query</em>}</li>
 * </ul>
 *
 * @see d4m.acc.query.d4MQuery.D4MQueryPackage#getD4MQuery()
 * @model
 * @generated
 */
public interface D4MQuery extends EObject
{
  /**
   * Returns the value of the '<em><b>Query</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Query</em>' containment reference.
   * @see #setQuery(QueryExpr)
   * @see d4m.acc.query.d4MQuery.D4MQueryPackage#getD4MQuery_Query()
   * @model containment="true"
   * @generated
   */
  QueryExpr getQuery();

  /**
   * Sets the value of the '{@link d4m.acc.query.d4MQuery.D4MQuery#getQuery <em>Query</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Query</em>' containment reference.
   * @see #getQuery()
   * @generated
   */
  void setQuery(QueryExpr value);

} // D4MQuery
