/**
 * generated by Xtext 2.39.0
 */
package d4m.acc.query.d4MQuery;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see d4m.acc.query.d4MQuery.D4MQueryPackage
 * @generated
 */
public interface D4MQueryFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  D4MQueryFactory eINSTANCE = d4m.acc.query.d4MQuery.impl.D4MQueryFactoryImpl.init();

  /**
   * Returns a new object of class '<em>D4M Query</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>D4M Query</em>'.
   * @generated
   */
  D4MQuery createD4MQuery();

  /**
   * Returns a new object of class '<em>Query Expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Query Expr</em>'.
   * @generated
   */
  QueryExpr createQueryExpr();

  /**
   * Returns a new object of class '<em>Axis Expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Axis Expr</em>'.
   * @generated
   */
  AxisExpr createAxisExpr();

  /**
   * Returns a new object of class '<em>Row Col Wildcard</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Row Col Wildcard</em>'.
   * @generated
   */
  RowColWildcard createRowColWildcard();

  /**
   * Returns a new object of class '<em>Range Expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Range Expr</em>'.
   * @generated
   */
  RangeExpr createRangeExpr();

  /**
   * Returns a new object of class '<em>List Expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>List Expr</em>'.
   * @generated
   */
  ListExpr createListExpr();

  /**
   * Returns a new object of class '<em>Starts With Expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Starts With Expr</em>'.
   * @generated
   */
  StartsWithExpr createStartsWithExpr();

  /**
   * Returns a new object of class '<em>Regex Expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Regex Expr</em>'.
   * @generated
   */
  RegexExpr createRegexExpr();

  /**
   * Returns a new object of class '<em>Literal Expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Literal Expr</em>'.
   * @generated
   */
  LiteralExpr createLiteralExpr();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  D4MQueryPackage getD4MQueryPackage();

} //D4MQueryFactory
