/**
 * generated by Xtext 2.39.0
 */
package d4m.acc.query.d4MQuery;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>List Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link d4m.acc.query.d4MQuery.ListExpr#getValues <em>Values</em>}</li>
 * </ul>
 *
 * @see d4m.acc.query.d4MQuery.D4MQueryPackage#getListExpr()
 * @model
 * @generated
 */
public interface ListExpr extends AxisExpr
{
  /**
   * Returns the value of the '<em><b>Values</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Values</em>' attribute list.
   * @see d4m.acc.query.d4MQuery.D4MQueryPackage#getListExpr_Values()
   * @model unique="false"
   * @generated
   */
  EList<String> getValues();

} // ListExpr
