/**
 * generated by Xtext 2.39.0
 */
package d4m.acc.query.d4MQuery;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Literal Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link d4m.acc.query.d4MQuery.LiteralExpr#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see d4m.acc.query.d4MQuery.D4MQueryPackage#getLiteralExpr()
 * @model
 * @generated
 */
public interface LiteralExpr extends AxisExpr
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see d4m.acc.query.d4MQuery.D4MQueryPackage#getLiteralExpr_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link d4m.acc.query.d4MQuery.LiteralExpr#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // LiteralExpr
