/**
 * generated by Xtext 2.39.0
 */
package d4m.acc.query.d4MQuery;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Query Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link d4m.acc.query.d4MQuery.QueryExpr#getRow <em>Row</em>}</li>
 *   <li>{@link d4m.acc.query.d4MQuery.QueryExpr#getCol <em>Col</em>}</li>
 * </ul>
 *
 * @see d4m.acc.query.d4MQuery.D4MQueryPackage#getQueryExpr()
 * @model
 * @generated
 */
public interface QueryExpr extends EObject
{
  /**
   * Returns the value of the '<em><b>Row</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Row</em>' containment reference.
   * @see #setRow(AxisExpr)
   * @see d4m.acc.query.d4MQuery.D4MQueryPackage#getQueryExpr_Row()
   * @model containment="true"
   * @generated
   */
  AxisExpr getRow();

  /**
   * Sets the value of the '{@link d4m.acc.query.d4MQuery.QueryExpr#getRow <em>Row</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Row</em>' containment reference.
   * @see #getRow()
   * @generated
   */
  void setRow(AxisExpr value);

  /**
   * Returns the value of the '<em><b>Col</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Col</em>' containment reference.
   * @see #setCol(AxisExpr)
   * @see d4m.acc.query.d4MQuery.D4MQueryPackage#getQueryExpr_Col()
   * @model containment="true"
   * @generated
   */
  AxisExpr getCol();

  /**
   * Sets the value of the '{@link d4m.acc.query.d4MQuery.QueryExpr#getCol <em>Col</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Col</em>' containment reference.
   * @see #getCol()
   * @generated
   */
  void setCol(AxisExpr value);

} // QueryExpr
