/**
 * generated by Xtext 2.39.0
 */
package d4m.acc.query.d4MQuery;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Range Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link d4m.acc.query.d4MQuery.RangeExpr#getFrom <em>From</em>}</li>
 *   <li>{@link d4m.acc.query.d4MQuery.RangeExpr#getTo <em>To</em>}</li>
 * </ul>
 *
 * @see d4m.acc.query.d4MQuery.D4MQueryPackage#getRangeExpr()
 * @model
 * @generated
 */
public interface RangeExpr extends AxisExpr
{
  /**
   * Returns the value of the '<em><b>From</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From</em>' attribute.
   * @see #setFrom(String)
   * @see d4m.acc.query.d4MQuery.D4MQueryPackage#getRangeExpr_From()
   * @model
   * @generated
   */
  String getFrom();

  /**
   * Sets the value of the '{@link d4m.acc.query.d4MQuery.RangeExpr#getFrom <em>From</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From</em>' attribute.
   * @see #getFrom()
   * @generated
   */
  void setFrom(String value);

  /**
   * Returns the value of the '<em><b>To</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>To</em>' attribute.
   * @see #setTo(String)
   * @see d4m.acc.query.d4MQuery.D4MQueryPackage#getRangeExpr_To()
   * @model
   * @generated
   */
  String getTo();

  /**
   * Sets the value of the '{@link d4m.acc.query.d4MQuery.RangeExpr#getTo <em>To</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To</em>' attribute.
   * @see #getTo()
   * @generated
   */
  void setTo(String value);

} // RangeExpr
