/**
 * generated by Xtext 2.39.0
 */
package d4m.acc.query.d4MQuery;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Regex Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link d4m.acc.query.d4MQuery.RegexExpr#getPattern <em>Pattern</em>}</li>
 * </ul>
 *
 * @see d4m.acc.query.d4MQuery.D4MQueryPackage#getRegexExpr()
 * @model
 * @generated
 */
public interface RegexExpr extends AxisExpr
{
  /**
   * Returns the value of the '<em><b>Pattern</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pattern</em>' attribute.
   * @see #setPattern(String)
   * @see d4m.acc.query.d4MQuery.D4MQueryPackage#getRegexExpr_Pattern()
   * @model
   * @generated
   */
  String getPattern();

  /**
   * Sets the value of the '{@link d4m.acc.query.d4MQuery.RegexExpr#getPattern <em>Pattern</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pattern</em>' attribute.
   * @see #getPattern()
   * @generated
   */
  void setPattern(String value);

} // RegexExpr
