/**
 * generated by Xtext 2.39.0
 */
package d4m.acc.query.d4MQuery;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Row Col Wildcard</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see d4m.acc.query.d4MQuery.D4MQueryPackage#getRowColWildcard()
 * @model
 * @generated
 */
public interface RowColWildcard extends AxisExpr
{
} // RowColWildcard
