/**
 * generated by Xtext 2.39.0
 */
package d4m.acc.query.d4MQuery;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Starts With Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link d4m.acc.query.d4MQuery.StartsWithExpr#getPrefix <em>Prefix</em>}</li>
 * </ul>
 *
 * @see d4m.acc.query.d4MQuery.D4MQueryPackage#getStartsWithExpr()
 * @model
 * @generated
 */
public interface StartsWithExpr extends AxisExpr
{
  /**
   * Returns the value of the '<em><b>Prefix</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prefix</em>' attribute.
   * @see #setPrefix(String)
   * @see d4m.acc.query.d4MQuery.D4MQueryPackage#getStartsWithExpr_Prefix()
   * @model
   * @generated
   */
  String getPrefix();

  /**
   * Sets the value of the '{@link d4m.acc.query.d4MQuery.StartsWithExpr#getPrefix <em>Prefix</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prefix</em>' attribute.
   * @see #getPrefix()
   * @generated
   */
  void setPrefix(String value);

} // StartsWithExpr
