services:
  insight_calc:
    build:
      context: .
      dockerfile: Dockerfile
    image: insight_calc:latest
    container_name: insight_calc
    ports:
      - "5201:5201"
    environment:
      - HAZOO_BASE_URL=http://host.docker.internal:5102
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
