#!/usr/bin/env bash
set -euo pipefail

# ── Templates ─────────────────────────────────────────────────────────────────

hosts_template() {
    local external_ip="$1"
    cat <<EOF
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
# Added by Docker Desktop
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
127.0.0.1 abend2.local abend2
10.101.3.161 hazoo
${external_ip} insight
EOF
}

ssh_template() {
    local external_ip="$1"
    cat <<EOF
# For threadedblue account
Host gh-threadedblue
    HostName github.com
    User git
    IdentityFile ~/.ssh/id_rsa
    IdentitiesOnly yes

# For semirings account
Host gh-semirings
    HostName github.com
    User git
    IdentityFile ~/.ssh/id_ed25519_semirings
    IdentitiesOnly yes

# Google Compute Engine Section
#
# The following has been auto-generated by "gcloud compute config-ssh"
# to make accessing your Google Compute Engine virtual machines easier.
#
# To remove this blob, run:
#
#   gcloud compute config-ssh --remove
#
# You can also manually remove this blob by deleting everything from
# here until the comment that contains the string "End of Google Compute
# Engine Section".
#
# You should not hand-edit this section, unless you are deleting it.
#
Host insight-dev-node.us-central1-a.creator-d4m-2026-1774038056
    HostName ${external_ip}
    IdentityFile /Users/gcr/.ssh/google_compute_engine
    UserKnownHostsFile=/Users/gcr/.ssh/google_compute_known_hosts
    HostKeyAlias=compute.2475492816028797449
    IdentitiesOnly=yes
    CheckHostIP=no

# End of Google Compute Engine Section
EOF
}

# ── Main ──────────────────────────────────────────────────────────────────────

usage() {
    echo "Usage: $(basename "$0") <option>"
    echo "  -up   start  insight-dev-node"
    echo "  -dn   stop   insight-dev-node"
    echo "  -st   status insight-dev-node"
    exit 1
}

[[ $# -eq 1 ]] || usage

case "$1" in
    -up) cmd="start"    ;;
    -dn) cmd="stop"     ;;
    -st) cmd="describe" ;;
    *)   usage          ;;
esac

gcloud compute instances "$cmd" insight-dev-node --zone=us-central1-a

if [[ "$cmd" == "start" ]]; then
    external_ip=$(gcloud compute instances describe insight-dev-node \
        --zone=us-central1-a \
        --format="get(networkInterfaces[0].accessConfigs[0].natIP)")
    echo "External IP: $external_ip"

    hosts_template "$external_ip" | sudo tee /etc/hosts > /dev/null
    echo "Replaced /etc/hosts: insight -> $external_ip"

    ssh_template "$external_ip" > ~/.ssh/config
    echo "Replaced ~/.ssh/config: insight -> $external_ip"
fi
