/*
 * generated by Xtext 2.39.0
 */
package d4m.acc.query.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class D4MQueryGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class D4MQueryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "d4m.acc.query.D4MQuery.D4MQuery");
		private final Assignment cQueryAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cQueryQueryExprParserRuleCall_0 = (RuleCall)cQueryAssignment.eContents().get(0);
		
		//D4MQuery:
		//    query=QueryExpr
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//query=QueryExpr
		public Assignment getQueryAssignment() { return cQueryAssignment; }
		
		//QueryExpr
		public RuleCall getQueryQueryExprParserRuleCall_0() { return cQueryQueryExprParserRuleCall_0; }
	}
	public class QueryExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "d4m.acc.query.D4MQuery.QueryExpr");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cRowAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cRowAxisExprParserRuleCall_0_0 = (RuleCall)cRowAssignment_0.eContents().get(0);
		private final Keyword cCommaKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cColAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cColAxisExprParserRuleCall_2_0 = (RuleCall)cColAssignment_2.eContents().get(0);
		
		//QueryExpr:
		//    row=AxisExpr ',' col=AxisExpr
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//row=AxisExpr ',' col=AxisExpr
		public Group getGroup() { return cGroup; }
		
		//row=AxisExpr
		public Assignment getRowAssignment_0() { return cRowAssignment_0; }
		
		//AxisExpr
		public RuleCall getRowAxisExprParserRuleCall_0_0() { return cRowAxisExprParserRuleCall_0_0; }
		
		//','
		public Keyword getCommaKeyword_1() { return cCommaKeyword_1; }
		
		//col=AxisExpr
		public Assignment getColAssignment_2() { return cColAssignment_2; }
		
		//AxisExpr
		public RuleCall getColAxisExprParserRuleCall_2_0() { return cColAxisExprParserRuleCall_2_0; }
	}
	public class AxisExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "d4m.acc.query.D4MQuery.AxisExpr");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cRowColWildcardParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cRangeExprParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cListExprParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cStartsWithExprParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cRegexExprParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cLiteralExprParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		
		//AxisExpr:
		//      RowColWildcard
		//    | RangeExpr
		//    | ListExpr
		//    | StartsWithExpr
		//    | RegexExpr
		//    | LiteralExpr
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//  RowColWildcard
		//| RangeExpr
		//| ListExpr
		//| StartsWithExpr
		//| RegexExpr
		//| LiteralExpr
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//RowColWildcard
		public RuleCall getRowColWildcardParserRuleCall_0() { return cRowColWildcardParserRuleCall_0; }
		
		//RangeExpr
		public RuleCall getRangeExprParserRuleCall_1() { return cRangeExprParserRuleCall_1; }
		
		//ListExpr
		public RuleCall getListExprParserRuleCall_2() { return cListExprParserRuleCall_2; }
		
		//StartsWithExpr
		public RuleCall getStartsWithExprParserRuleCall_3() { return cStartsWithExprParserRuleCall_3; }
		
		//RegexExpr
		public RuleCall getRegexExprParserRuleCall_4() { return cRegexExprParserRuleCall_4; }
		
		//LiteralExpr
		public RuleCall getLiteralExprParserRuleCall_5() { return cLiteralExprParserRuleCall_5; }
	}
	public class RowColWildcardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "d4m.acc.query.D4MQuery.RowColWildcard");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRowColWildcardAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//RowColWildcard returns RowColWildcard:
		//    {RowColWildcard} ':'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{RowColWildcard} ':'
		public Group getGroup() { return cGroup; }
		
		//{RowColWildcard}
		public Action getRowColWildcardAction_0() { return cRowColWildcardAction_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
	}
	public class RangeExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "d4m.acc.query.D4MQuery.RangeExpr");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cFromAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cFromSTRINGTerminalRuleCall_0_0 = (RuleCall)cFromAssignment_0.eContents().get(0);
		private final Keyword cFullStopFullStopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cToAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cToSTRINGTerminalRuleCall_2_0 = (RuleCall)cToAssignment_2.eContents().get(0);
		
		//RangeExpr:
		//    from=STRING '..' to=STRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//from=STRING '..' to=STRING
		public Group getGroup() { return cGroup; }
		
		//from=STRING
		public Assignment getFromAssignment_0() { return cFromAssignment_0; }
		
		//STRING
		public RuleCall getFromSTRINGTerminalRuleCall_0_0() { return cFromSTRINGTerminalRuleCall_0_0; }
		
		//'..'
		public Keyword getFullStopFullStopKeyword_1() { return cFullStopFullStopKeyword_1; }
		
		//to=STRING
		public Assignment getToAssignment_2() { return cToAssignment_2; }
		
		//STRING
		public RuleCall getToSTRINGTerminalRuleCall_2_0() { return cToSTRINGTerminalRuleCall_2_0; }
	}
	public class ListExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "d4m.acc.query.D4MQuery.ListExpr");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cValuesAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cValuesAlternatives_1_0 = (Alternatives)cValuesAssignment_1.eContents().get(0);
		private final RuleCall cValuesSTRINGTerminalRuleCall_1_0_0 = (RuleCall)cValuesAlternatives_1_0.eContents().get(0);
		private final RuleCall cValuesIDTerminalRuleCall_1_0_1 = (RuleCall)cValuesAlternatives_1_0.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCommaKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cValuesAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final Alternatives cValuesAlternatives_2_1_0 = (Alternatives)cValuesAssignment_2_1.eContents().get(0);
		private final RuleCall cValuesSTRINGTerminalRuleCall_2_1_0_0 = (RuleCall)cValuesAlternatives_2_1_0.eContents().get(0);
		private final RuleCall cValuesIDTerminalRuleCall_2_1_0_1 = (RuleCall)cValuesAlternatives_2_1_0.eContents().get(1);
		private final Keyword cRightSquareBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//ListExpr:
		//    '[' values+=(STRING | ID) (',' values+=(STRING | ID))* ']'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'[' values+=(STRING | ID) (',' values+=(STRING | ID))* ']'
		public Group getGroup() { return cGroup; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_0() { return cLeftSquareBracketKeyword_0; }
		
		//values+=(STRING | ID)
		public Assignment getValuesAssignment_1() { return cValuesAssignment_1; }
		
		//(STRING | ID)
		public Alternatives getValuesAlternatives_1_0() { return cValuesAlternatives_1_0; }
		
		//STRING
		public RuleCall getValuesSTRINGTerminalRuleCall_1_0_0() { return cValuesSTRINGTerminalRuleCall_1_0_0; }
		
		//ID
		public RuleCall getValuesIDTerminalRuleCall_1_0_1() { return cValuesIDTerminalRuleCall_1_0_1; }
		
		//(',' values+=(STRING | ID))*
		public Group getGroup_2() { return cGroup_2; }
		
		//','
		public Keyword getCommaKeyword_2_0() { return cCommaKeyword_2_0; }
		
		//values+=(STRING | ID)
		public Assignment getValuesAssignment_2_1() { return cValuesAssignment_2_1; }
		
		//(STRING | ID)
		public Alternatives getValuesAlternatives_2_1_0() { return cValuesAlternatives_2_1_0; }
		
		//STRING
		public RuleCall getValuesSTRINGTerminalRuleCall_2_1_0_0() { return cValuesSTRINGTerminalRuleCall_2_1_0_0; }
		
		//ID
		public RuleCall getValuesIDTerminalRuleCall_2_1_0_1() { return cValuesIDTerminalRuleCall_2_1_0_1; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_3() { return cRightSquareBracketKeyword_3; }
	}
	public class StartsWithExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "d4m.acc.query.D4MQuery.StartsWithExpr");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStartsWithKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cPrefixAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Alternatives cPrefixAlternatives_2_0 = (Alternatives)cPrefixAssignment_2.eContents().get(0);
		private final RuleCall cPrefixSTRINGTerminalRuleCall_2_0_0 = (RuleCall)cPrefixAlternatives_2_0.eContents().get(0);
		private final RuleCall cPrefixIDTerminalRuleCall_2_0_1 = (RuleCall)cPrefixAlternatives_2_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//StartsWithExpr:
		//    'StartsWith' '(' prefix=(STRING | ID) ')'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'StartsWith' '(' prefix=(STRING | ID) ')'
		public Group getGroup() { return cGroup; }
		
		//'StartsWith'
		public Keyword getStartsWithKeyword_0() { return cStartsWithKeyword_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//prefix=(STRING | ID)
		public Assignment getPrefixAssignment_2() { return cPrefixAssignment_2; }
		
		//(STRING | ID)
		public Alternatives getPrefixAlternatives_2_0() { return cPrefixAlternatives_2_0; }
		
		//STRING
		public RuleCall getPrefixSTRINGTerminalRuleCall_2_0_0() { return cPrefixSTRINGTerminalRuleCall_2_0_0; }
		
		//ID
		public RuleCall getPrefixIDTerminalRuleCall_2_0_1() { return cPrefixIDTerminalRuleCall_2_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
	}
	public class RegexExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "d4m.acc.query.D4MQuery.RegexExpr");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRegexKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cPatternAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Alternatives cPatternAlternatives_2_0 = (Alternatives)cPatternAssignment_2.eContents().get(0);
		private final RuleCall cPatternSTRINGTerminalRuleCall_2_0_0 = (RuleCall)cPatternAlternatives_2_0.eContents().get(0);
		private final RuleCall cPatternIDTerminalRuleCall_2_0_1 = (RuleCall)cPatternAlternatives_2_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//RegexExpr:
		//    'Regex' '(' pattern=(STRING | ID) ')'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Regex' '(' pattern=(STRING | ID) ')'
		public Group getGroup() { return cGroup; }
		
		//'Regex'
		public Keyword getRegexKeyword_0() { return cRegexKeyword_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//pattern=(STRING | ID)
		public Assignment getPatternAssignment_2() { return cPatternAssignment_2; }
		
		//(STRING | ID)
		public Alternatives getPatternAlternatives_2_0() { return cPatternAlternatives_2_0; }
		
		//STRING
		public RuleCall getPatternSTRINGTerminalRuleCall_2_0_0() { return cPatternSTRINGTerminalRuleCall_2_0_0; }
		
		//ID
		public RuleCall getPatternIDTerminalRuleCall_2_0_1() { return cPatternIDTerminalRuleCall_2_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
	}
	public class LiteralExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "d4m.acc.query.D4MQuery.LiteralExpr");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final Alternatives cValueAlternatives_0 = (Alternatives)cValueAssignment.eContents().get(0);
		private final RuleCall cValueSTRINGTerminalRuleCall_0_0 = (RuleCall)cValueAlternatives_0.eContents().get(0);
		private final RuleCall cValueIDTerminalRuleCall_0_1 = (RuleCall)cValueAlternatives_0.eContents().get(1);
		
		//LiteralExpr:
		//    value=(STRING | ID)
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//value=(STRING | ID)
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//(STRING | ID)
		public Alternatives getValueAlternatives_0() { return cValueAlternatives_0; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_0_0() { return cValueSTRINGTerminalRuleCall_0_0; }
		
		//ID
		public RuleCall getValueIDTerminalRuleCall_0_1() { return cValueIDTerminalRuleCall_0_1; }
	}
	
	
	private final D4MQueryElements pD4MQuery;
	private final QueryExprElements pQueryExpr;
	private final AxisExprElements pAxisExpr;
	private final RowColWildcardElements pRowColWildcard;
	private final RangeExprElements pRangeExpr;
	private final ListExprElements pListExpr;
	private final StartsWithExprElements pStartsWithExpr;
	private final RegexExprElements pRegexExpr;
	private final LiteralExprElements pLiteralExpr;
	private final TerminalRule tID;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public D4MQueryGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pD4MQuery = new D4MQueryElements();
		this.pQueryExpr = new QueryExprElements();
		this.pAxisExpr = new AxisExprElements();
		this.pRowColWildcard = new RowColWildcardElements();
		this.pRangeExpr = new RangeExprElements();
		this.pListExpr = new ListExprElements();
		this.pStartsWithExpr = new StartsWithExprElements();
		this.pRegexExpr = new RegexExprElements();
		this.pLiteralExpr = new LiteralExprElements();
		this.tID = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "d4m.acc.query.D4MQuery.ID");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("d4m.acc.query.D4MQuery".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//D4MQuery:
	//    query=QueryExpr
	//;
	public D4MQueryElements getD4MQueryAccess() {
		return pD4MQuery;
	}
	
	public ParserRule getD4MQueryRule() {
		return getD4MQueryAccess().getRule();
	}
	
	//QueryExpr:
	//    row=AxisExpr ',' col=AxisExpr
	//;
	public QueryExprElements getQueryExprAccess() {
		return pQueryExpr;
	}
	
	public ParserRule getQueryExprRule() {
		return getQueryExprAccess().getRule();
	}
	
	//AxisExpr:
	//      RowColWildcard
	//    | RangeExpr
	//    | ListExpr
	//    | StartsWithExpr
	//    | RegexExpr
	//    | LiteralExpr
	//;
	public AxisExprElements getAxisExprAccess() {
		return pAxisExpr;
	}
	
	public ParserRule getAxisExprRule() {
		return getAxisExprAccess().getRule();
	}
	
	//RowColWildcard returns RowColWildcard:
	//    {RowColWildcard} ':'
	//;
	public RowColWildcardElements getRowColWildcardAccess() {
		return pRowColWildcard;
	}
	
	public ParserRule getRowColWildcardRule() {
		return getRowColWildcardAccess().getRule();
	}
	
	//RangeExpr:
	//    from=STRING '..' to=STRING
	//;
	public RangeExprElements getRangeExprAccess() {
		return pRangeExpr;
	}
	
	public ParserRule getRangeExprRule() {
		return getRangeExprAccess().getRule();
	}
	
	//ListExpr:
	//    '[' values+=(STRING | ID) (',' values+=(STRING | ID))* ']'
	//;
	public ListExprElements getListExprAccess() {
		return pListExpr;
	}
	
	public ParserRule getListExprRule() {
		return getListExprAccess().getRule();
	}
	
	//StartsWithExpr:
	//    'StartsWith' '(' prefix=(STRING | ID) ')'
	//;
	public StartsWithExprElements getStartsWithExprAccess() {
		return pStartsWithExpr;
	}
	
	public ParserRule getStartsWithExprRule() {
		return getStartsWithExprAccess().getRule();
	}
	
	//RegexExpr:
	//    'Regex' '(' pattern=(STRING | ID) ')'
	//;
	public RegexExprElements getRegexExprAccess() {
		return pRegexExpr;
	}
	
	public ParserRule getRegexExprRule() {
		return getRegexExprAccess().getRule();
	}
	
	//LiteralExpr:
	//    value=(STRING | ID)
	//;
	public LiteralExprElements getLiteralExprAccess() {
		return pLiteralExpr;
	}
	
	public ParserRule getLiteralExprRule() {
		return getLiteralExprAccess().getRule();
	}
	
	//terminal ID:
	//    ('a'..'z' | 'A'..'Z' | '_')
	//    ('a'..'z' | 'A'..'Z' | '0'..'9' | '_' | '.' | '-')*;
	public TerminalRule getIDRule() {
		return tID;
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
