/*
 * generated by Xtext 2.39.0
 */
package d4m.acc.query.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractD4MQueryScopeProvider extends DelegatingScopeProvider {
}
