/**
 * generated by Xtext 2.39.0
 */
package d4m.acc.query.d4MQuery.util;

import d4m.acc.query.d4MQuery.*;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see d4m.acc.query.d4MQuery.D4MQueryPackage
 * @generated
 */
public class D4MQueryAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static D4MQueryPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public D4MQueryAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = D4MQueryPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected D4MQuerySwitch<Adapter> modelSwitch =
    new D4MQuerySwitch<Adapter>()
    {
      @Override
      public Adapter caseD4MQuery(D4MQuery object)
      {
        return createD4MQueryAdapter();
      }
      @Override
      public Adapter caseQueryExpr(QueryExpr object)
      {
        return createQueryExprAdapter();
      }
      @Override
      public Adapter caseAxisExpr(AxisExpr object)
      {
        return createAxisExprAdapter();
      }
      @Override
      public Adapter caseRowColWildcard(RowColWildcard object)
      {
        return createRowColWildcardAdapter();
      }
      @Override
      public Adapter caseRangeExpr(RangeExpr object)
      {
        return createRangeExprAdapter();
      }
      @Override
      public Adapter caseListExpr(ListExpr object)
      {
        return createListExprAdapter();
      }
      @Override
      public Adapter caseStartsWithExpr(StartsWithExpr object)
      {
        return createStartsWithExprAdapter();
      }
      @Override
      public Adapter caseRegexExpr(RegexExpr object)
      {
        return createRegexExprAdapter();
      }
      @Override
      public Adapter caseLiteralExpr(LiteralExpr object)
      {
        return createLiteralExprAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link d4m.acc.query.d4MQuery.D4MQuery <em>D4M Query</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see d4m.acc.query.d4MQuery.D4MQuery
   * @generated
   */
  public Adapter createD4MQueryAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link d4m.acc.query.d4MQuery.QueryExpr <em>Query Expr</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see d4m.acc.query.d4MQuery.QueryExpr
   * @generated
   */
  public Adapter createQueryExprAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link d4m.acc.query.d4MQuery.AxisExpr <em>Axis Expr</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see d4m.acc.query.d4MQuery.AxisExpr
   * @generated
   */
  public Adapter createAxisExprAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link d4m.acc.query.d4MQuery.RowColWildcard <em>Row Col Wildcard</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see d4m.acc.query.d4MQuery.RowColWildcard
   * @generated
   */
  public Adapter createRowColWildcardAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link d4m.acc.query.d4MQuery.RangeExpr <em>Range Expr</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see d4m.acc.query.d4MQuery.RangeExpr
   * @generated
   */
  public Adapter createRangeExprAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link d4m.acc.query.d4MQuery.ListExpr <em>List Expr</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see d4m.acc.query.d4MQuery.ListExpr
   * @generated
   */
  public Adapter createListExprAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link d4m.acc.query.d4MQuery.StartsWithExpr <em>Starts With Expr</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see d4m.acc.query.d4MQuery.StartsWithExpr
   * @generated
   */
  public Adapter createStartsWithExprAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link d4m.acc.query.d4MQuery.RegexExpr <em>Regex Expr</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see d4m.acc.query.d4MQuery.RegexExpr
   * @generated
   */
  public Adapter createRegexExprAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link d4m.acc.query.d4MQuery.LiteralExpr <em>Literal Expr</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see d4m.acc.query.d4MQuery.LiteralExpr
   * @generated
   */
  public Adapter createLiteralExprAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //D4MQueryAdapterFactory
