// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjEzAti9bsFDPq2NErpfCHDh7mT-g6xrU',
    appId: '1:899702095630:web:f03f2286d0bb7d68fee15f',
    messagingSenderId: '899702095630',
    projectId: 'creator-d4m-2026-1774038-183b7',
    authDomain: 'creator-d4m-2026-1774038-183b7.firebaseapp.com',
    storageBucket: 'creator-d4m-2026-1774038-183b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvPST3px_AgmoQv9DhDThMB8dooiQaKTI',
    appId: '1:899702095630:android:df0f12d8f977887afee15f',
    messagingSenderId: '899702095630',
    projectId: 'creator-d4m-2026-1774038-183b7',
    storageBucket: 'creator-d4m-2026-1774038-183b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCURfk_c5gfpGcpTWLjyxGqHUshr_2aHWw',
    appId: '1:899702095630:ios:bf8625acf996bcd7fee15f',
    messagingSenderId: '899702095630',
    projectId: 'creator-d4m-2026-1774038-183b7',
    storageBucket: 'creator-d4m-2026-1774038-183b7.firebasestorage.app',
    iosBundleId: 'com.example.insightVisual',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCURfk_c5gfpGcpTWLjyxGqHUshr_2aHWw',
    appId: '1:899702095630:ios:bf8625acf996bcd7fee15f',
    messagingSenderId: '899702095630',
    projectId: 'creator-d4m-2026-1774038-183b7',
    storageBucket: 'creator-d4m-2026-1774038-183b7.firebasestorage.app',
    iosBundleId: 'com.example.insightVisual',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjEzAti9bsFDPq2NErpfCHDh7mT-g6xrU',
    appId: '1:899702095630:web:53bf1f6e2e1a692ffee15f',
    messagingSenderId: '899702095630',
    projectId: 'creator-d4m-2026-1774038-183b7',
    authDomain: 'creator-d4m-2026-1774038-183b7.firebaseapp.com',
    storageBucket: 'creator-d4m-2026-1774038-183b7.firebasestorage.app',
  );
}
