services:
  insight_visual:
    build:
      context: .
      dockerfile: Dockerfile
    image: insight_visual:latest
    container_name: insight_visual
    ports:
      - "5200:5200"
    restart: unless-stopped

