version: "3.9"

services:
  insight_store:
    build:
      context: .
      dockerfile: Dockerfile
    image: insight_store:latest
    container_name: insight_store
    ports:
      - "5202:5202"
      - "9997:9997"
    environment:
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - BIGQUERY_DATASET=${BIGQUERY_DATASET:-d4m}
    volumes:
      - ./client.properties:/app/client.properties
