services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  insight_store:
    build:
      context: .
      dockerfile: Dockerfile
    image: insight_store:latest
    container_name: insight_store
    ports:
      - "5202:5202"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - redis