/**
 * generated by Xtext 2.39.0
 */
package d4m.acc.query.d4MQuery.impl;

import d4m.acc.query.d4MQuery.AxisExpr;
import d4m.acc.query.d4MQuery.D4MQueryPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Axis Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AxisExprImpl extends MinimalEObjectImpl.Container implements AxisExpr
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AxisExprImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return D4MQueryPackage.Literals.AXIS_EXPR;
  }

} //AxisExprImpl
