/**
 * generated by Xtext 2.39.0
 */
package d4m.acc.query.d4MQuery.impl;

import d4m.acc.query.d4MQuery.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class D4MQueryFactoryImpl extends EFactoryImpl implements D4MQueryFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static D4MQueryFactory init()
  {
    try
    {
      D4MQueryFactory theD4MQueryFactory = (D4MQueryFactory)EPackage.Registry.INSTANCE.getEFactory(D4MQueryPackage.eNS_URI);
      if (theD4MQueryFactory != null)
      {
        return theD4MQueryFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new D4MQueryFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public D4MQueryFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case D4MQueryPackage.D4M_QUERY: return createD4MQuery();
      case D4MQueryPackage.QUERY_EXPR: return createQueryExpr();
      case D4MQueryPackage.AXIS_EXPR: return createAxisExpr();
      case D4MQueryPackage.ROW_COL_WILDCARD: return createRowColWildcard();
      case D4MQueryPackage.RANGE_EXPR: return createRangeExpr();
      case D4MQueryPackage.LIST_EXPR: return createListExpr();
      case D4MQueryPackage.STARTS_WITH_EXPR: return createStartsWithExpr();
      case D4MQueryPackage.REGEX_EXPR: return createRegexExpr();
      case D4MQueryPackage.LITERAL_EXPR: return createLiteralExpr();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public D4MQuery createD4MQuery()
  {
    D4MQueryImpl d4MQuery = new D4MQueryImpl();
    return d4MQuery;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public QueryExpr createQueryExpr()
  {
    QueryExprImpl queryExpr = new QueryExprImpl();
    return queryExpr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AxisExpr createAxisExpr()
  {
    AxisExprImpl axisExpr = new AxisExprImpl();
    return axisExpr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RowColWildcard createRowColWildcard()
  {
    RowColWildcardImpl rowColWildcard = new RowColWildcardImpl();
    return rowColWildcard;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RangeExpr createRangeExpr()
  {
    RangeExprImpl rangeExpr = new RangeExprImpl();
    return rangeExpr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ListExpr createListExpr()
  {
    ListExprImpl listExpr = new ListExprImpl();
    return listExpr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StartsWithExpr createStartsWithExpr()
  {
    StartsWithExprImpl startsWithExpr = new StartsWithExprImpl();
    return startsWithExpr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RegexExpr createRegexExpr()
  {
    RegexExprImpl regexExpr = new RegexExprImpl();
    return regexExpr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LiteralExpr createLiteralExpr()
  {
    LiteralExprImpl literalExpr = new LiteralExprImpl();
    return literalExpr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public D4MQueryPackage getD4MQueryPackage()
  {
    return (D4MQueryPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static D4MQueryPackage getPackage()
  {
    return D4MQueryPackage.eINSTANCE;
  }

} //D4MQueryFactoryImpl
