/**
 * generated by Xtext 2.39.0
 */
package d4m.acc.query.d4MQuery.impl;

import d4m.acc.query.d4MQuery.D4MQueryPackage;
import d4m.acc.query.d4MQuery.RowColWildcard;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Row Col Wildcard</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RowColWildcardImpl extends AxisExprImpl implements RowColWildcard
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RowColWildcardImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return D4MQueryPackage.Literals.ROW_COL_WILDCARD;
  }

} //RowColWildcardImpl
