/*
 * generated by Xtext 2.39.0
 */
package d4m.acc.query.serializer;

import com.google.inject.Inject;
import d4m.acc.query.d4MQuery.D4MQuery;
import d4m.acc.query.d4MQuery.D4MQueryPackage;
import d4m.acc.query.d4MQuery.ListExpr;
import d4m.acc.query.d4MQuery.LiteralExpr;
import d4m.acc.query.d4MQuery.QueryExpr;
import d4m.acc.query.d4MQuery.RangeExpr;
import d4m.acc.query.d4MQuery.RegexExpr;
import d4m.acc.query.d4MQuery.RowColWildcard;
import d4m.acc.query.d4MQuery.StartsWithExpr;
import d4m.acc.query.services.D4MQueryGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class D4MQuerySemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private D4MQueryGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == D4MQueryPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case D4MQueryPackage.D4M_QUERY:
				sequence_D4MQuery(context, (D4MQuery) semanticObject); 
				return; 
			case D4MQueryPackage.LIST_EXPR:
				sequence_ListExpr(context, (ListExpr) semanticObject); 
				return; 
			case D4MQueryPackage.LITERAL_EXPR:
				sequence_LiteralExpr(context, (LiteralExpr) semanticObject); 
				return; 
			case D4MQueryPackage.QUERY_EXPR:
				sequence_QueryExpr(context, (QueryExpr) semanticObject); 
				return; 
			case D4MQueryPackage.RANGE_EXPR:
				sequence_RangeExpr(context, (RangeExpr) semanticObject); 
				return; 
			case D4MQueryPackage.REGEX_EXPR:
				sequence_RegexExpr(context, (RegexExpr) semanticObject); 
				return; 
			case D4MQueryPackage.ROW_COL_WILDCARD:
				sequence_RowColWildcard(context, (RowColWildcard) semanticObject); 
				return; 
			case D4MQueryPackage.STARTS_WITH_EXPR:
				sequence_StartsWithExpr(context, (StartsWithExpr) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     D4MQuery returns D4MQuery
	 *
	 * Constraint:
	 *     query=QueryExpr
	 * </pre>
	 */
	protected void sequence_D4MQuery(ISerializationContext context, D4MQuery semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, D4MQueryPackage.Literals.D4M_QUERY__QUERY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, D4MQueryPackage.Literals.D4M_QUERY__QUERY));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getD4MQueryAccess().getQueryQueryExprParserRuleCall_0(), semanticObject.getQuery());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AxisExpr returns ListExpr
	 *     ListExpr returns ListExpr
	 *
	 * Constraint:
	 *     ((values+=STRING | values+=ID) values+=STRING? (values+=ID? values+=STRING?)*)
	 * </pre>
	 */
	protected void sequence_ListExpr(ISerializationContext context, ListExpr semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AxisExpr returns LiteralExpr
	 *     LiteralExpr returns LiteralExpr
	 *
	 * Constraint:
	 *     (value=STRING | value=ID)
	 * </pre>
	 */
	protected void sequence_LiteralExpr(ISerializationContext context, LiteralExpr semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     QueryExpr returns QueryExpr
	 *
	 * Constraint:
	 *     (row=AxisExpr col=AxisExpr)
	 * </pre>
	 */
	protected void sequence_QueryExpr(ISerializationContext context, QueryExpr semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, D4MQueryPackage.Literals.QUERY_EXPR__ROW) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, D4MQueryPackage.Literals.QUERY_EXPR__ROW));
			if (transientValues.isValueTransient(semanticObject, D4MQueryPackage.Literals.QUERY_EXPR__COL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, D4MQueryPackage.Literals.QUERY_EXPR__COL));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getQueryExprAccess().getRowAxisExprParserRuleCall_0_0(), semanticObject.getRow());
		feeder.accept(grammarAccess.getQueryExprAccess().getColAxisExprParserRuleCall_2_0(), semanticObject.getCol());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AxisExpr returns RangeExpr
	 *     RangeExpr returns RangeExpr
	 *
	 * Constraint:
	 *     (from=STRING to=STRING)
	 * </pre>
	 */
	protected void sequence_RangeExpr(ISerializationContext context, RangeExpr semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, D4MQueryPackage.Literals.RANGE_EXPR__FROM) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, D4MQueryPackage.Literals.RANGE_EXPR__FROM));
			if (transientValues.isValueTransient(semanticObject, D4MQueryPackage.Literals.RANGE_EXPR__TO) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, D4MQueryPackage.Literals.RANGE_EXPR__TO));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRangeExprAccess().getFromSTRINGTerminalRuleCall_0_0(), semanticObject.getFrom());
		feeder.accept(grammarAccess.getRangeExprAccess().getToSTRINGTerminalRuleCall_2_0(), semanticObject.getTo());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AxisExpr returns RegexExpr
	 *     RegexExpr returns RegexExpr
	 *
	 * Constraint:
	 *     (pattern=STRING | pattern=ID)
	 * </pre>
	 */
	protected void sequence_RegexExpr(ISerializationContext context, RegexExpr semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AxisExpr returns RowColWildcard
	 *     RowColWildcard returns RowColWildcard
	 *
	 * Constraint:
	 *     {RowColWildcard}
	 * </pre>
	 */
	protected void sequence_RowColWildcard(ISerializationContext context, RowColWildcard semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AxisExpr returns StartsWithExpr
	 *     StartsWithExpr returns StartsWithExpr
	 *
	 * Constraint:
	 *     (prefix=STRING | prefix=ID)
	 * </pre>
	 */
	protected void sequence_StartsWithExpr(ISerializationContext context, StartsWithExpr semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
