/*
 * generated by Xtext 2.39.0
 */
package d4m.acc.query.parser.antlr;

import com.google.inject.Inject;
import d4m.acc.query.parser.antlr.internal.InternalD4MQueryParser;
import d4m.acc.query.services.D4MQueryGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class D4MQueryParser extends AbstractAntlrParser {

	@Inject
	private D4MQueryGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalD4MQueryParser createParser(XtextTokenStream stream) {
		return new InternalD4MQueryParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "D4MQuery";
	}

	public D4MQueryGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(D4MQueryGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
