/*
 * generated by Xtext 2.39.0
 */
package d4m.acc.query.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class D4MQueryAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("d4m/acc/query/parser/antlr/internal/InternalD4MQuery.tokens");
	}
}
