/*
 * generated by Xtext 2.39.0
 */
package d4m.acc.query;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class D4MQueryRuntimeModule extends AbstractD4MQueryRuntimeModule {
}
