/*
 * generated by Xtext 2.39.0
 */
package d4m.acc.query;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class D4MQueryStandaloneSetup extends D4MQueryStandaloneSetupGenerated {

	public static void doSetup() {
		new D4MQueryStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
