server.port=5202
management.endpoints.web.exposure.include=*

# Show full health details
management.endpoint.health.show-details=always

# Limits for POST bodies
server.tomcat.max-http-post-size=2097152   # 2MB in bytes
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# BigQuery configuration
bigquery.project-id=${GOOGLE_CLOUD_PROJECT}
bigquery.dataset-id=${BIGQUERY_DATASET:d4m}