project_id    = "creator-d4m-2026-1774038056"
artifact_repo = "insight-repo"
zone          = "us-central1-a"
bucket        = "insightcircle_bucket"
region        = "us-central1"
pubsub_subscription = "store-process-sub"
